"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from gui.config import version

APP = ['mmass.py']
DATA_FILES = [
    ('configs',[
        'configs/monomers.xml',
        'configs/compounds.xml',
        'configs/config.xml',
        'configs/enzymes.xml',
        'configs/mascot.xml',
        'configs/modifications.xml',
        'configs/presets.xml',
        'configs/references.xml',
    ]),
    ('',[
        'license.txt',
        'README.md',
        'User Guide.pdf',
    ])
]
OPTIONS = {
    'iconfile': 'gui/images/mac/icon.icns',
    'argv_emulation': 1,
    'compressed': 1,
    'optimize': 1,
    'plist': {
        'CFBundleName': 'mMass',
        'CFBundleDisplayName': 'mMass',
        'CFBundleExecutable': 'mMass',
        'CFBundleSignature': 'mMass',
        'CFBundleIdentifier': 'org.mmass',
        'CFBundlePackageType': 'APPL',
        'CFBundleShortVersionString': version,
        'CFBundleVersion': version,
        'CFBundleGetInfoString': 'mMass - Open Source Mass Spectrometry Tool',
        'CFBundleIconFile': 'icon.icns',
        'NSHumanReadableCopyright': '(c) 2005-2013 Martin Strohalm, 2020-2021 Dreaming Spires',
        'LSHasLocalizedDisplayName': False,
        'NSAppleScriptEnabled': False,
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeExtensions': ['msd'],
                'CFBundleTypeName': 'mMass Spectrum Document',
                'CFBundleTypeIconFile': 'icon_doc_msd.icns',
                'CFBundleTypeOSTypes': ['TEXT'],
                'CFBundleTypeRole': 'Editor',
                'NSDocumentClass': 'MyDocument',
            },
            {
                'CFBundleTypeExtensions': ['mzdata'],
                'CFBundleTypeName': 'mzData Mass Spectrum Document',
                'CFBundleTypeIconFile': 'icon_doc_mzdata.icns',
                'CFBundleTypeOSTypes': ['TEXT'],
                'CFBundleTypeRole': 'Viewer',
                'NSDocumentClass': 'MyDocument',
            },
            {
                'CFBundleTypeExtensions': ['mzxml'],
                'CFBundleTypeName': 'mzXML Mass Spectrum Document',
                'CFBundleTypeIconFile': 'icon_doc_mzxml.icns',
                'CFBundleTypeOSTypes': ['TEXT'],
                'CFBundleTypeRole': 'Viewer',
                'NSDocumentClass': 'MyDocument',
            },
            {
                'CFBundleTypeExtensions': ['mzml'],
                'CFBundleTypeName': 'mzML Mass Spectrum Document',
                'CFBundleTypeIconFile': 'icon_doc_mzml.icns',
                'CFBundleTypeOSTypes': ['TEXT'],
                'CFBundleTypeRole': 'Viewer',
                'NSDocumentClass': 'MyDocument',
            },
            {
                'CFBundleTypeExtensions': ['mgf'],
                'CFBundleTypeName': 'Mascot Generic Format',
                'CFBundleTypeIconFile': 'icon_doc_mgf.icns',
                'CFBundleTypeOSTypes': ['TEXT'],
                'CFBundleTypeRole': 'Viewer',
                'NSDocumentClass': 'MyDocument',
            }
        ]
    }
}

additionalFiles = [
	'gui/images/mac/icon_doc_msd.icns',
	'gui/images/mac/icon_doc_mzdata.icns',
	'gui/images/mac/icon_doc_mzxml.icns',
	'gui/images/mac/icon_doc_mzml.icns',
	'gui/images/mac/icon_doc_fid.icns',
	'configs',
	'User Guide.pdf'
]

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    author = 'Martin Strohalm',
    url = 'https://github.com/dreamingspires/mMass',
    license = 'GPLv3'
)
